apiVersion: nais.io/v1
kind: Alert
metadata:
  name: raptus-alerts
  namespace: raptus
  labels:
    team: raptus
spec:
  receivers:
    slack:
      channel: '#team-raptus-alerts-dev'
  alerts:
    # Sjekker om en eller flere applikasjoner er nede i namespacet, dvs. at det ikke finnes noen kjørende podder
    - alert: Applikasjon er nede
      expr: kube_deployment_status_replicas_available{namespace="{{ namespace }}"} == 0
      for: 3m
      description: '*\{{ $labels.deployment }}* er nede i namespace \{{ $labels.namespace }}.'
      action: 'Kjør `kubectl describe pod -l app=\{{ $labels.deployment }} -n \{{ $labels.namespace }}` for å se events, og `kubectl logs -l app=\{{ $labels.deployment }} -n \{{ $labels.namespace }}` for logger. Sjekk også Kibana for eventuelle feil som er logget, query `application: \{{ $labels.deployment }} AND (level:Error OR level:Warning)`.'
      severity: danger


